version: '3.3'

services:
  web:
    build: ./etc/php/
    container_name: it_web
    volumes:
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini:delegated"
      - "./logs/php:/var/log/php-scripts.log:delegated"
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf:delegated"
      - "../:/var/www/html:delegated"
      - "../static/:/var/www/static:delegated"
      - "./logs/nginx:/var/log/nginx:delegated"
    ports:
      - "80:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: it_mysql
    env_file:
      - ".env"
    command:
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
    ports:
      - "3310:3306"
    volumes:
      - "./data/db/mysql:/var/lib/mysql:delegated"
      - "./mysql/:/etc/mysql/conf.d/"


